/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package engtelecom.std;

import org.glassfish.jersey.client.ClientConfig;

import jakarta.ws.rs.client.Client;
import jakarta.ws.rs.client.ClientBuilder;
import jakarta.ws.rs.client.WebTarget;
import jakarta.ws.rs.core.MediaType;
import jakarta.ws.rs.core.UriBuilder;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        String URI = "http://localhost:8080/";
        Client client = ClientBuilder.newClient(new ClientConfig());
        WebTarget target = client.target(UriBuilder.fromUri(URI).build());
        String resposta = target.path("saudacao").request().accept(MediaType.APPLICATION_JSON).get(String.class);
        System.out.println(resposta);
    }
}
